#############################################################################
# Makefile for building: FacebookTouchQt
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mon 13. Sep 19:15:03 2021
# Project:  FacebookTouchQt.pro
# Template: app
# Command: c:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe -spec ..\..\..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf FacebookTouchQt.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQ_COMPONENTS_SYMBIAN -DHAVE_MOBILITY -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtCore"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtNetwork"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtGui"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtWebKit"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtDeclarative"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/mkspecs/common/symbian"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/sys"  -I"C:/Users/Unknown/Desktop/FacebookTouchQt/qmlapplicationviewer"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/mw"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/stlportv5"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtXmlPatterns"  -I"C:/Users/Unknown/Desktop/FacebookTouchQt/moc"  -I"C:/Users/Unknown/Desktop/FacebookTouchQt"  -I"C:/Users/Unknown/Desktop/FacebookTouchQt/rcc"  -I"C:/Users/Unknown/Desktop/FacebookTouchQt/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "C:/Users/Unknown/Desktop/FacebookTouchQt/FacebookTouchQt.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/Users/Unknown/Desktop/FacebookTouchQt/FacebookTouchQt.pro
	$(QMAKE) "C:/Users/Unknown/Desktop/FacebookTouchQt/FacebookTouchQt.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc: 
	$(QMAKE) "C:/Users/Unknown/Desktop/FacebookTouchQt/FacebookTouchQt.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/release/winscw/udeb/FacebookTouchQt.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis FacebookTouchQt.sis FacebookTouchQt.exe $(QT_RUN_OPTIONS)

FacebookTouchQt_template.pkg: C:/Users/Unknown/Desktop/FacebookTouchQt/FacebookTouchQt.pro
	$(MAKE) -f $(MAKEFILE) qmake

FacebookTouchQt_installer.pkg: C:/Users/Unknown/Desktop/FacebookTouchQt/FacebookTouchQt.pro
	$(MAKE) -f $(MAKEFILE) qmake

FacebookTouchQt_stub.pkg: C:/Users/Unknown/Desktop/FacebookTouchQt/FacebookTouchQt.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: FacebookTouchQt_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) FacebookTouchQt_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: FacebookTouchQt_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o FacebookTouchQt_template.pkg $(QT_SIS_TARGET)

FacebookTouchQt.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: FacebookTouchQt_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: FacebookTouchQt_installer.pkg
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) FacebookTouchQt_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: FacebookTouchQt_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: FacebookTouchQt_installer.pkg
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o FacebookTouchQt_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: FacebookTouchQt_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) FacebookTouchQt_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call FacebookTouchQt.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_networkaccessmanagerinteractor.cpp moc\moc_qmlutils.cpp moc\moc_mediakeysobserver.cpp moc\moc_qdeclarativewebview.cpp moc\moc_screenclass.cpp moc\moc_useragent.cpp moc\moc_settings.cpp moc\moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_networkaccessmanagerinteractor.cpp moc\moc_qmlutils.cpp moc\moc_mediakeysobserver.cpp moc\moc_qdeclarativewebview.cpp moc\moc_screenclass.cpp moc\moc_useragent.cpp moc\moc_settings.cpp moc\moc_qmlapplicationviewer.cpp
moc\moc_networkaccessmanagerinteractor.cpp: networkaccessmanagerinteractor.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Unknown\Desktop\FacebookTouchQt\networkaccessmanagerinteractor.h -o c:\Users\Unknown\Desktop\FacebookTouchQt\moc\moc_networkaccessmanagerinteractor.cpp

moc\moc_qmlutils.cpp: qmlutils.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Unknown\Desktop\FacebookTouchQt\qmlutils.h -o c:\Users\Unknown\Desktop\FacebookTouchQt\moc\moc_qmlutils.cpp

moc\moc_mediakeysobserver.cpp: mediakeysobserver.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Unknown\Desktop\FacebookTouchQt\mediakeysobserver.h -o c:\Users\Unknown\Desktop\FacebookTouchQt\moc\moc_mediakeysobserver.cpp

moc\moc_qdeclarativewebview.cpp: qdeclarativewebview.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Unknown\Desktop\FacebookTouchQt\qdeclarativewebview.h -o c:\Users\Unknown\Desktop\FacebookTouchQt\moc\moc_qdeclarativewebview.cpp

moc\moc_screenclass.cpp: screenclass.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Unknown\Desktop\FacebookTouchQt\screenclass.h -o c:\Users\Unknown\Desktop\FacebookTouchQt\moc\moc_screenclass.cpp

moc\moc_useragent.cpp: useragent.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Unknown\Desktop\FacebookTouchQt\useragent.h -o c:\Users\Unknown\Desktop\FacebookTouchQt\moc\moc_useragent.cpp

moc\moc_settings.cpp: settings.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Unknown\Desktop\FacebookTouchQt\settings.h -o c:\Users\Unknown\Desktop\FacebookTouchQt\moc\moc_settings.cpp

moc\moc_qmlapplicationviewer.cpp: qmlapplicationviewer\qmlapplicationviewer.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Unknown\Desktop\FacebookTouchQt\qmlapplicationviewer\qmlapplicationviewer.h -o c:\Users\Unknown\Desktop\FacebookTouchQt\moc\moc_qmlapplicationviewer.cpp

compiler_rcc_make_all: rcc\qrc_symbian-res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc\qrc_symbian-res.cpp
rcc\qrc_symbian-res.cpp: symbian-res.qrc \
		qml\FacebookTouchQt\PSW.qml \
		qml\FacebookTouchQt\About.qml \
		qml\FacebookTouchQt\OtherAppsDialog.qml \
		qml\FacebookTouchQt\ImageViewer.qml \
		qml\FacebookTouchQt\SettingsBasePage.qml \
		qml\FacebookTouchQt\TouchPage.qml \
		qml\FacebookTouchQt\FullscreenTouch.qml \
		qml\FacebookTouchQt\NormalPopup.qml \
		qml\FacebookTouchQt\MobilePage.qml \
		qml\FacebookTouchQt\FullscreenPopup.qml \
		qml\FacebookTouchQt\HideView.qml \
		qml\FacebookTouchQt\SignupPage.qml \
		qml\FacebookTouchQt\MediaKeysDialog.qml \
		qml\FacebookTouchQt\UrlInput.qml \
		qml\FacebookTouchQt\ExitDialog.qml \
		qml\FacebookTouchQt\CookieClearDialog.qml \
		qml\FacebookTouchQt\MainPage.qml \
		qml\FacebookTouchQt\NightCover.qml \
		qml\FacebookTouchQt\main.qml \
		qml\FacebookTouchQt\FullscreenMobile.qml \
		qml\FacebookTouchQt\MenuPage.qml \
		qml\FacebookTouchQt\Decorator.qml \
		qml\FacebookTouchQt\HelpBaseDialog.qml \
		qml\FacebookTouchQt\SecondWindowMobile.qml \
		qml\FacebookTouchQt\NetworkProxyPage.qml \
		qml\FacebookTouchQt\VersionChangesPopup.qml \
		qml\FacebookTouchQt\Extras.qml \
		qml\FacebookTouchQt\images\facebook.svg \
		qml\FacebookTouchQt\images\close_stop.svg \
		qml\FacebookTouchQt\images\store.svg \
		qml\FacebookTouchQt\images\twitter.svg \
		qml\FacebookTouchQt\images\back.svg \
		qml\FacebookTouchQt\images\icon.svg \
		qml\FacebookTouchQt\images\save.svg \
		qml\FacebookTouchQt\images\toolmenu.svg \
		qml\FacebookTouchQt\Component\SenseToolButton.qml \
		qml\FacebookTouchQt\Component\AutoReloadPopup.qml \
		qml\FacebookTouchQt\Component\SenseListItemDisabled.qml \
		qml\FacebookTouchQt\Component\ZoomPopup.qml \
		qml\FacebookTouchQt\Component\PrivacyDialog.qml \
		qml\FacebookTouchQt\Component\TouchMenu.qml \
		qml\FacebookTouchQt\Component\SubItemIndicator.qml \
		qml\FacebookTouchQt\Component\BottomBar.qml \
		qml\FacebookTouchQt\Component\ListItemSenseSettings.qml \
		qml\FacebookTouchQt\Component\SenseButton.qml \
		qml\FacebookTouchQt\Component\UserAgentPicker.qml \
		qml\FacebookTouchQt\Component\CustomUA.qml \
		qml\FacebookTouchQt\Component\FadingLoader.qml \
		qml\FacebookTouchQt\Component\ButtonTip.qml \
		qml\FacebookTouchQt\Component\SenseButtonNoWidth.qml \
		qml\FacebookTouchQt\Component\OpacityBlocker.qml \
		qml\FacebookTouchQt\Component\ListHead.qml \
		qml\FacebookTouchQt\Component\ListItemSense.qml \
		qml\FacebookTouchQt\Component\MobileShortcutsPopup.qml \
		qml\FacebookTouchQt\Component\FontSizeChooser.qml \
		qml\FacebookTouchQt\Component\MobileMenu.qml \
		qml\FacebookTouchQt\Component\ProgressBar.qml \
		qml\FacebookTouchQt\Component\ListItemSenseTwoWay.qml \
		qml\FacebookTouchQt\Component\NightIntensityToggle.qml \
		qml\FacebookTouchQt\Component\SecondWindowMenu.qml \
		qml\FacebookTouchQt\Fullscreen\Controls.qml \
		qml\FacebookTouchQt\Fullscreen\FullscreenMenu.qml \
		splash\splash.png
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\rcc.exe -name symbian-res c:\Users\Unknown\Desktop\FacebookTouchQt\symbian-res.qrc -o c:\Users\Unknown\Desktop\FacebookTouchQt\rcc\qrc_symbian-res.cpp

compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

dodistclean:
	-@ if EXIST "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt_template.pkg" $(DEL_FILE)  "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt_template.pkg"
	-@ if EXIST "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt_stub.pkg" $(DEL_FILE)  "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt_stub.pkg"
	-@ if EXIST "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt_installer.pkg" $(DEL_FILE)  "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt_installer.pkg"
	-@ if EXIST "c:\Users\Unknown\Desktop\FacebookTouchQt\Makefile" $(DEL_FILE)  "c:\Users\Unknown\Desktop\FacebookTouchQt\Makefile"
	-@ if EXIST "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt_exe.mmp" $(DEL_FILE)  "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt_exe.mmp"
	-@ if EXIST "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt_reg.rss" $(DEL_FILE)  "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt_reg.rss"
	-@ if EXIST "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.rss" $(DEL_FILE)  "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.rss"
	-@ if EXIST "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc" $(DEL_FILE)  "c:\Users\Unknown\Desktop\FacebookTouchQt\FacebookTouchQt.loc"
	-@ if EXIST "c:\Users\Unknown\Desktop\FacebookTouchQt\bld.inf" $(DEL_FILE)  "c:\Users\Unknown\Desktop\FacebookTouchQt\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


